### ISSUE TITLE
Idek tbh

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#114]
RangeError [EMBED_DESCRIPTION]: MessageEmbed description must be a string.
    at Function.verifyString (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setDescription (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/structures/MessageEmbed.js:412:29)
    at Object.run (/var/lib/pufferpanel/servers/6a3aa38e/src/events/Client/rateLimit.js:7:87)
    at MusicBot.<anonymous> (/var/lib/pufferpanel/servers/6a3aa38e/src/structures/MusicClient.js:88:44)
    at MusicBot.emit (node:events:390:28)
    at RequestHandler.execute (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/rest/RequestHandler.js:131:29)
    at RequestHandler.push (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/rest/RequestHandler.js:51:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TextChannel.send (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:175:15) {
  [Symbol(code)]: 'EMBED_DESCRIPTION'

**Comment by liloko** [comment]
but how to fix this?
