### ISSUE TITLE
Lyrics command not working

### ISSUE THREAD

**Issue by giabao06** [brblacky/lavamusic#136]
**Describe the bug**
As said in title. 

**To Reproduce**
Use the lyrics command.

**Expected behavior**
An embed of the lyric of the currently playing song should appear

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Discord App
 - Version Stable 118205 (081ceba), Host 0.0.17

**Smartphone (please complete the following information):** 
(Since the error is not related to smartphones, I guess I will not be filling this out untill required)

**Additional context**
Error thrown:
```
RangeError [EMBED_DESCRIPTION]: MessageEmbed description must be a string.
    at Function.verifyString (/mnt/musicbots/1d/node_modules/discord.js/src/util/Util.js:416:41)
    at MessageEmbed.setDescription (/mnt/musicbots/1d/node_modules/discord.js/src/structures/MessageEmbed.js:412:29)
    at Object.execute (/mnt/musicbots/1d/src/commands/Music/lyrics.js:34:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'EMBED_DESCRIPTION'
}
```
Server info: Ubuntu 20.04 LTS aarch64, Node v17.0.1.

**Comment by RennJs** [comment]
I have the fixed code dm me at cord Renn#0007

**Comment by TEDDY6969** [comment]
https://pastebin.com/H8W0wLa6

**Comment by brblacky** [comment]
@TEDDY6969 
GitHub push it
