### ISSUE TITLE
to resolve

### ISSUE THREAD

**Issue by LucasB25** [brblacky/lavamusic#150]
TypeError: Cannot read properties of undefined (reading '0')
    at Object.run (C:\Users\LucasB25\Desktop\lava\src\events\Client\voiceStateUpdate.js:65:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[13-06-2022 04:08:57]: [WARN] Node "lavalink.oops.wtf" disconnect because [object Object].

TypeError: Cannot read properties of null (reading 'identifier')
    at Object.run (C:\Users\LucasB25\Desktop\lava\src\slashCommands\Music\autoplay.js:25:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (C:\Users\LucasB25\Desktop\lava\src\events\Client\interactionCreate.js:119:9)

**Comment by LucasB25** [comment]
I had not yet received the proposal for a sweater.
From what I saw, you did a little work on one of the four remaining errors that were listed

**Comment by ShibaInu0413** [comment]
> I had not yet received the proposal for a sweater. From what I saw, you did a little work on one of the four remaining errors that were listed

I solved all 4 problems
Two of them were resolved in my last PR
The other two are actually one a problem

**Comment by LucasB25** [comment]
ah! so much for me. thank you

**Comment by ShibaInu0413** [comment]
> ah! so much for me. thank you

I'm happy to solve your problem
