### ISSUE TITLE
TypeError: this.nowPlayingMessage.delete is not a function

### ISSUE THREAD

**Issue by codemeister64** [brblacky/lavamusic#158]
**Describe the bug**
error in docker container console:
```bash
TypeError: this.nowPlayingMessage.delete is not a function
    at lavaplayer.setNowplayingMessage (/opt/lavamusic/src/structures/PlayerBase.js:18:40)
    at module.exports (/opt/lavamusic/src/events/Lavalink/trackStart.js:29:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```

**To Reproduce**
install bot via docker (tag main) and start playing sporify playlist

**Expected behavior**
bot messages should be deleted from channel

**Comment by LucasB25** [comment]
Report original issues #150
