### ISSUE TITLE
/setupmusic set broke for me

### ISSUE THREAD

**Issue by Gremagol** [brblacky/lavamusic#172]
**Describe the bug**
`/setupmusic set` has stopped working after some time, whenever I use it it says this:

```
Error [GUILD_CHANNEL_RESOLVE]: Could not resolve channel to a guild channel.
     at GuildMember.permissionsIn (/root/HatKid/Music/lavamusic/node_modules/discord.js/src/structures/GuildMember.js:326:25)
     at Object.run (/root/HatKid/Music/lavamusic/src/slashCommands/Config/setup.js:41:10)
     at Object.run (/root/HatKid/Music/lavamusic/src/events/Client/interactionCreate.js:86:37)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
   [Symbol(code)]: 'GUILD_CHANNEL_RESOLVE'
 }
```

**To Reproduce**
1. I only ran the command
2. It stopped working.

**Expected behavior**
That it works as expected, Channels generate, no error.

**Screenshots**
When it worked: https://gyazo.com/6045355c1ca198421967ad903f0643fc
When it stopped: https://gyazo.com/d7d1fdec7692c6bb4424acfed07ba2e7
When it stopped it drops this error above.

**Desktop (please complete the following information):**
VPS:
OS: Ubuntu 22.04 LTS
CPU: AMD EPYC 7702P 64-Core Processor
Discord.js : v13.8.1
Node : v18.4.0

**Comment by Gremagol** [comment]
**UPDATE:** It only seems to happen when I am not in a Voice Channel!
