### ISSUE TITLE
cant run bot

### ISSUE THREAD

**Issue by THUNDER1090** [brblacky/lavamusic#219]
 npx node src/index.js
/home/runner/lavamusic-3/node_modules/discord.js/src/util/Util.js:279
    if (!Object.hasOwn(given, key) || given[key] === undefined) {
                ^

TypeError: Object.hasOwn is not a function
    at mergeDefault (/home/runner/lavamusic-3/node_modules/discord.js/src/util/Util.js:279:17)
    at new BaseClient (/home/runner/lavamusic-3/node_modules/discord.js/src/client/BaseClient.js:25:20)
    at new Client (/home/runner/lavamusic-3/node_modules/discord.js/src/client/Client.js:43:5)
    at new MusicBot (/home/runner/lavamusic-3/src/structures/Client.js:7:5)
    at Object.<anonymous> (/home/runner/lavamusic-3/src/index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
exit status 1
 s^C

**Comment by THUNDER1090** [comment]
help!
