### ISSUE TITLE
coming this error while using play command

### ISSUE THREAD

**Issue by Habeeb30** [brblacky/lavamusic#229]
2022-07-29T10:13:22.134269+00:00 app[worker.1]: SyntaxError: Unexpected token  in JSON at position 0
2022-07-29T10:13:22.134277+00:00 app[worker.1]:     at JSON.parse (<anonymous>)
2022-07-29T10:13:22.134278+00:00 app[worker.1]:     at Y.json (/app/node_modules/petitio/dist/index.js:30:574)
2022-07-29T10:13:22.134279+00:00 app[worker.1]:     at ke.json (/app/node_modules/petitio/dist/index.js:30:2499)
2022-07-29T10:13:22.134280+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-07-29T10:13:22.135158+00:00 app[worker.1]: TypeError: Cannot read properties of undefined (reading 'loadType')
2022-07-29T10:13:22.135158+00:00 app[worker.1]:     at Object.run (/app/src/slashCommands/Music/play.js:95:17)
2022-07-29T10:13:22.135158+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-07-29T10:13:22.135158+00:00 app[worker.1]:     at async Object.run (/app/src/events/Client/interactionCreate.js:98:9)

**Comment by LucasB25** [comment]
Update node.js v16

**Comment by Gremagol** [comment]
This has to be reopened since a lot of people (including me) in the support channel report the same issue out of nowhere.

We made sure our nodes are on version 16.9

I've tried all nodes from 16.9 to 16.17, nothing changed
I've tried to use different lavalinks, same error
I've tried to reinstall the bot from scratch, same error

This should be investigated together.

**Comment by kartik-opbolte** [comment]
> 

yes same issue
