### ISSUE TITLE
no available nodes

### ISSUE THREAD

**Issue by ukcai696969** [brblacky/lavamusic#252]
`hi! ive clonded your bot and insterted all the info`
when i run the bot i get this error when trying to play songs
`RangeError: No available nodes.
    at new Player (/home/container/node_modules/erela.js/dist/structures/Player.js:82:19)
    at new <anonymous> (/home/container/src/structures/Lavamusic.js:12:5)
    at Lavamusic.create (/home/container/node_modules/erela.js/dist/structures/Manager.js:205:16)
    at Object.run (/home/container/src/slashCommands/Music/play.js:36:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (/home/container/src/events/Client/interactionCreate.js:88:17)
`

can anyone help ive change the lavalink details loads

**Comment by LucasB25** [comment]
user [16.16.0 LTS](https://nodejs.org/dist/v16.16.0/node-v16.16.0-x64.msi)

**Comment by typhonshambo** [comment]
i am using node 16.16.0 but still the error exists

**Comment by LucasB25** [comment]
You misplaced your lavalink server information

**Comment by typhonshambo** [comment]
i have given it in .env

like this
```
NODE_HOST=lava.moebot.xyz
NODE_ID=lava.moebot.xyz
NODE_PORT=80
NODE_PASSWORD=Blacky#9125
NODE_SECURE=false
```

**Comment by LucasB25** [comment]
![image](https://user-images.githubusercontent.com/50886682/185092620-c611ea13-f001-4697-bf1c-3f700a6909f3.png)

**Comment by Ukcai6** [comment]
I fixed it thanks
