### ISSUE TITLE
Bot doesn't show currently playing on track start when setup channel is deleted and shows an error 

### ISSUE THREAD

**Issue by RafCodez** [brblacky/lavamusic#269]
Bot wont show trackStart on `!play` when you delete the setup channel. It will keep showing 
```yaml
TypeError: Cannot read properties of undefined (reading 'id')
    at module.exports (/home/runner/lavamusic/src/events/Lavalink/trackStart.js:16:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'id')
      at module.exports (/home/runner/lavamusic/src/events/Lavalink/trackStart.js:16:36)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}
```
This error. Because data.Channel this channel doesn't exist. Instead make the bot send trackStart message on the channel where play was executed and send a message that setup channel was deleted instead of showing this error
![Screenshot_20220831-171930_Chrome](https://user-images.githubusercontent.com/89015458/187723048-e4c01206-c90b-47b7-8ebc-552b32ccb688.png)

Channel which was deleted shows as undefined when i do console.log in 16th line in src/events/Lavalink/trackStart.js 

![Screenshot_20220831-173845_Chrome](https://user-images.githubusercontent.com/89015458/187723257-e6b20213-645b-4ed2-977b-4a09598b210c.png)

**Comment by RafCodez** [comment]
No I didn't. But I could.

**Comment by LucasB25** [comment]
I might as well do it, and on the way I reported an error in the pull query which will therefore need to be set

**Comment by RafCodez** [comment]
Updated a few stuff can you have a look in it

**Comment by LucasB25** [comment]
And I’m thinking about this one, too?

**Comment by RafCodez** [comment]
No this isn't fixed. Let me see what can I do.

**Comment by LucasB25** [comment]
ok
