### ISSUE TITLE
Setup Resume Bug

### ISSUE THREAD

**Issue by RedolentHalo** [brblacky/lavamusic#288]
**Please describe the problem you are having in as much detail as possible:**

### Essentials:

- Commit Hash:
- Node.js version: 17
- Operating system: Windows

#### Additional system info
- Is it virtualized? (Docker or ...) : no
- What CPU is it running on (X86 or ARM or...): x86
- Additional details that might help us figure out the problem:
- Hey in the setup channel the music is not getting resumed when it says it's resumed please help it's an issue with voiceupdatestate.js It's working fine in the normal play command. It hasn't been fixed forever, I hope it gets fixed soon.

### Relevant client options:

- partials: all
- gateway intents: all
- other: none

![image](https://user-images.githubusercontent.com/86344714/190911248-db000b7c-95c7-42ee-af85-2d3a592f05e6.png)

**Comment by RedolentHalo** [comment]
TypeError: Cannot read properties of undefined (reading 'embeds')
    at Object.run (/home/container/src/events/Client/voiceStateUpdate.js:68:52)
    at MusicBot.<anonymous> (/home/container/src/handlers/events.js:7:50)
    at MusicBot.emit (node:events:527:28)
    at VoiceStateUpdate.handle (/home/container/node_modules/discord.js/src/client/actions/VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:481:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28) uncaughtException
TypeError: Cannot read properties of undefined (reading 'embeds')
    at Object.run (/home/container/src/events/Client/voiceStateUpdate.js:68:52)
    at MusicBot.<anonymous> (/home/container/src/handlers/events.js:7:50)
    at MusicBot.emit (node:events:527:28)
    at VoiceStateUpdate.handle (/home/container/node_modules/discord.js/src/client/actions/VoiceStateUpdate.js:38:14)
    at Object.module.exports [as VOICE_STATE_UPDATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/VOICE_STATE_UPDATE.js:4:35)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:481:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:321:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28) uncaughtException btw it is giving this error

**Comment by NotAditya69** [comment]
Use the latest source

**Comment by RedolentHalo** [comment]
It ain't working dude

**Comment by RedolentHalo** [comment]
OK BRO EVERYTHING IS CHANGED
