### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NevinMathewsOfficial** [brblacky/lavamusic#35]
Error: Cannot find module 'node:events'
Require stack:
- /home/runner/lavamusic/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/lavamusic/node_modules/discord.js/src/index.js
- /home/runner/lavamusic/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/lavamusic/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/lavamusic/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/lavamusic/node_modules/discord.js/src/index.js',
    '/home/runner/lavamusic/index.js'
  ]
}

im getting this error i have the index.js file but its sayin this

**Comment by brblacky** [comment]
Update your node version
