### ISSUE TITLE
slashhandler

### ISSUE THREAD

**Issue by pasindu20** [brblacky/lavamusic#386]
### Bug description

why slashhandler give this error 

### Operating system

win8

### Nodejs version

16.15.1

### Errors / Logs

```js
HTTPError: Internal Server Error
    at SequentialHandler.runRequest (C:\Users\user\Desktop\test\node_modules\@discordjs\rest\dist\index.js:652:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\user\Desktop\test\node_modules\@discordjs\rest\dist\index.js:458:14)
    at async REST.request (C:\Users\user\Desktop\test\node_modules\@discordjs\rest\dist\index.js:902:22)
    at async C:\Users\user\Desktop\test\src\handlers\slashcommand.js:36:7 {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object]
    ]
  },

  status: 500,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/id/commands'
}
```

**Comment by LucasB25** [comment]
Use node 18

**Comment by pasindu20** [comment]
issue has been resolved
