### ISSUE TITLE
Slash Help Error

### ISSUE THREAD

**Issue by penchuri** [brblacky/lavamusic#391]
### Bug description

When i do /help it show but after press the buttos it doest work

### Step to reproduce

Idk how rhis happen

### Operating system

linux

### Nodejs version

v17

### Errors / Logs

How i can fix this error on help slash

CombinedError (2)
  Received one or more errors

  1 ExpectedValidationError > s.literal(V)
  |   Expected values to be equals
  | 
  |   Expected:
  |   | null
  | 
  |   Received:
  |   | ''

  2 ExpectedConstraintError > s.string.lengthGreaterThanOrEqual
  |   Invalid string length
  | 
  |   Expected: expected.length >= 1
  | 
  |   Received:
  |   | ''

    at UnionValidator.handle (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:1058:23)
    at UnionValidator.parse (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:113:88)
    at EmbedBuilder.setDescription (/home/container/node_modules/@discordjs/builders/dist/index.js:231:26)
    at InteractionCollector.<anonymous> (/home/container/src/slashCommands/Information/help.js:60:52)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by LucasB25** [comment]
use node js 18

**Comment by penchuri** [comment]
> use node js 18

Still got same error
