### ISSUE TITLE
Help slash error

### ISSUE THREAD

**Issue by penchuri** [brblacky/lavamusic#395]
### Bug description

When do /help and press the button it doest work and send error in discord logs and in vps console
Error: Received one or more errors

### Step to reproduce

Not sure

### Operating system

linux

### Nodejs version

node 18 and 17

### Errors / Logs

Error: Received one or more errors

CombinedError (2)
  Received one or more errors
  1 ExpectedValidationError > s.literal(V)
  |   Expected values to be equals
  | 
  |   Expected:
  |   | null
  | 
  |   Received:
  |   | ''
  2 ExpectedConstraintError > s.string.lengthGreaterThanOrEqual
  |   Invalid string length
  | 
  |   Expected: expected.length >= 1
  | 
  |   Received:
  |   | ''
    at UnionValidator.handle (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:1051:23)
    at UnionValidator.parse (/home/container/node_modules/@sapphire/shapeshift/dist/index.js:106:88)
    at EmbedBuilder.setDescription (/home/container/node_modules/@discordjs/builders/dist/index.js:238:26)
    at InteractionCollector.<anonymous> (/home/container/src/slashCommands/Information/help.js:66:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by LucasB25** [comment]
still a current problem?

**Comment by penchuri** [comment]
Well the prob happen cause it doest get a any file in command category. you know how i can make on /help code it get command name in just slashcommands category

**Comment by LucasB25** [comment]
in this case you have to rely on the command messages not the slash, the code was not done for the categories of slash
