### ISSUE TITLE
Error [InteractionNotReplied]

### ISSUE THREAD

**Issue by aitronssesin** [brblacky/lavamusic#397]
### Bug description

Error in the console

### Step to reproduce

When the error happens the bot leaves the channel

### Operating system

Linux

### Nodejs version

18

### Errors / Logs

Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ButtonInteraction.followUp (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:184:64)
    at buttonReply (/home/container/src/utils/functions.js:378:15)
    at Object.run (/home/container/src/events/Client/playerButton.js:25:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InteractionNotReplied'
}

**Comment by LucasB25** [comment]
#225
