### ISSUE TITLE
Spotify bug

### ISSUE THREAD

**Issue by Krzysiekyt00** [brblacky/lavamusic#407]
### Bug description

 Spotify option "clientID" must be present and be a non-empty string.

### Step to reproduce

Pls help

### Operating system

Windows 10

### Nodejs version

18.12.1

### Errors / Logs

TypeError: Spotify option "clientID" must be present and be a non-empty string.
    at check (C:\Users\Administrator\Desktop\lavamusic-main\node_modules\erela.js-spotify\dist\plugin.js:37:15)
    at new Spotify (C:\Users\Administrator\Desktop\lavamusic-main\node_modules\erela.js-spotify\dist\plugin.js:53:9)
    at new Lavamusic (C:\Users\Administrator\Desktop\lavamusic-main\src\structures\Lavamusic.js:296:9)
    at new MusicBot (C:\Users\Administrator\Desktop\lavamusic-main\src\structures\Client.js:56:20)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\lavamusic-main\src\index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Node.js v18.12.1

**Comment by Krzysiekyt00** [comment]
I got it resolved

**Comment by Xenofic** [comment]
Provide your Spotify clientId from your Spotify dev dashboard
