### ISSUE TITLE
Bot crashes with "This node is not yet ready" after a specific amount of time if not connected to a VC

### ISSUE THREAD

**Issue by Legoman99573** [brblacky/lavamusic#416]
### Bug description

Noticed behavior when starting the bot, it will crash with the error "This node is not yet ready" like it is expecting to be connected to at least one Voice Channel in one guild in order to stay up and running.

### Step to reproduce

1. Start the server
2. Give it about 30 seconds to a minute
3. Crashes with given error in Error/Logs

### Operating system

Rocky Linux 8

### Nodejs version

v18.14.0

### Errors / Logs

up to date, audited 162 packages in 654ms
11 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
[2/14/2023] [4:31:14 AM] [Manager] › ▶  start     [CLIENT] 1 shard(s) spawned.
[2/14/2023] [4:31:15 AM] [Manager] › 🎫  event     Loaded 0 events
[2/14/2023] [4:31:15 AM] [Manager] › ✔️  ready     Connected to MongoDB
[2/14/2023] [4:31:15 AM] [Manager] › ⌨️  cmd       Successfully loaded 20 commands
[2/14/2023] [4:31:16 AM] [Manager] › ✔️  ready     Logged in as UgandaVRC Music#4712
[2/14/2023] [4:31:16 AM] [Manager] › ✔️  ready     Node LavaLink connected
/home/container/node_modules/shoukaku/dist/src/Shoukaku.js:93
            throw new Error('This node is not yet ready');
            ^
Error: This node is not yet ready
    at Shoukaku.getNode (/home/container/node_modules/shoukaku/dist/src/Shoukaku.js:93:19)
    at Shoukaku.<anonymous> (file:///home/container/src/structures/Shoukaku.js:50:52)
    at Shoukaku.emit (node:events:513:28)
    at Node.<anonymous> (/home/container/node_modules/shoukaku/dist/src/Shoukaku.js:61:44)
    at Node.emit (node:events:513:28)
    at Node.close (/home/container/node_modules/shoukaku/dist/src/node/Node.js:206:14)
    at WebSocket.<anonymous> (/home/container/node_modules/shoukaku/dist/src/node/Node.js:92:49)
    at Object.onceWrapper (node:events:628:26)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/home/container/node_modules/ws/lib/websocket.js:258:10)
Node.js v18.14.0

**Comment by Legoman99573** [comment]
Update: Just waiting for PR https://github.com/Deivu/Shoukaku/pull/135 to be pushed and it should start printing out the reason it disconnected and will attempt to re-connect and resume its last state before disconnecting.

**Comment by LucasB25** [comment]
ton serveur lavalain n'est pas correct
