### ISSUE TITLE
Errors in the console that I encountered.

### ISSUE THREAD

**Issue by WolverStones** [brblacky/lavamusic#430]
```
[3/21/2023] [7:08:16 PM] [aitiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> DiscordAPIError[10008]: Unknown Message
      at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:933:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:712:14)
      at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1321:22)
      at async InteractionWebhook.editMessage (/home/container/node_modules/discord.js/src/structures/Webhook.js:338:15)
      at async ChatInputCommandInteraction.editReply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:17)
      at async Context.editMessage (file:///home/container/dist/structures/Context.js:39:24)
      at async InteractionCollector.<anonymous> (file:///home/container/dist/commands/music/Search.js:104:13) {
    rawError: { message: 'Unknown Message', code: 10008 },
    code: 10008,
    status: 404,
    method: 'PATCH',
    url: 'https://discord.com/api/v10/webhooks/1002649346032029706/aW50ZXJhY3Rpb246MTA4NzgxNDcwNDMwNDUwMDc4Njo5aWZHMXZQZDVnbkk5RHJHdkU2S1I5dFJIMlZlUXRrVHdudGZucVpsNmNrUkMxMWxVdDhBWnNqTTFxaHBmOXdVSDVIZUNQS0JjYWdCRXQwemZ6Z1dDbmdJU0tJRm5yZHp3YWRRNk80MDBzZlhaUDQ0N1BFNUJ0WWk0ejl2Wml0bw/messages/@original',
    requestBody: { files: [], json: [Object] }
  }
} reason: DiscordAPIError[10008]: Unknown Message
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:933:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async InteractionWebhook.editMessage (/home/container/node_modules/discord.js/src/structures/Webhook.js:338:15)
    at async ChatInputCommandInteraction.editReply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:158:17)
    at async Context.editMessage (file:///home/container/dist/structures/Context.js:39:24)
    at async InteractionCollector.<anonymous> (file:///home/container/dist/commands/music/Search.js:104:13) {
  rawError: { message: 'Unknown Message', code: 10008 },
  code: 10008,
  status: 404,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/webhooks/1002649346032029706/aW50ZXJhY3Rpb246MTA4NzgxNDcwNDMwNDUwMDc4Njo5aWZHMXZQZDVnbkk5RHJHdkU2S1I5dFJIMlZlUXRrVHdudGZucVpsNmNrUkMxMWxVdDhBWnNqTTFxaHBmOXdVSDVIZUNQS0JjYWdCRXQwemZ6Z1dDbmdJU0tJRm5yZHp3YWRRNk80MDBzZlhaUDQ0N1BFNUJ0WWk0ejl2Wml0bw/messages/@original',
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: [],
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  }
}
```

```
[3/21/2023] [9:54:08 PM] [InteractionCreate.js] [Lavamusic] › ✖  error     TypeError: Cannot read properties of undefined (reading 'createMessageComponentCollector') 
    at Search.run (file:///home/container/dist/commands/music/Search.js:83:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:113:17)

```

```
[3/21/2023] [9:54:09 PM] [aitiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: DiscordAPIError[40060]: Interaction has already been acknowledged.
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:933:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:712:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1321:22)
    at async ChatInputCommandInteraction.reply (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async InteractionCreate.run (file:///home/container/dist/events/client/InteractionCreate.js:117:17) {
  rawError: {
    message: 'Interaction has already been acknowledged.',
    code: 40060
  },
  code: 40060,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1087856537554387084/aW50ZXJhY3Rpb246MTA4Nzg1NjUzNzU1NDM4NzA4NDpkVUZ6ekI0a2ZqYTBOb2J0RzJLaGFTWWpVY0lUSUNZNXp2bHRDS01nQXZCNXhQTThPZVluV2FsbTFvRjZ1YXh6aGZPMWRodDRwSTVoQkdLenRxeGl4OWRCYWdkNUdwa3BwUE1MT1FwckFZZ3NKQ0RIMGtMbXdjdFM1QXBjaTdYQg/callback',
  requestBody: { files: [], json: { type: 4, data: [Object] } }
}
```

**Comment by brblacky** [comment]
Fixed
https://github.com/brblacky/lavamusic/commit/242b06d3529329fa0b4efaa06f7d0578ef0d415c

**Comment by babico** [comment]
I got little a bit similar error
```log
```log
discord-lavamusic            | [4/14/2023] [12:42:54 AM] [aitiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
discord-lavamusic            |   <rejected> DiscordAPIError[10062]: Unknown interaction
discord-lavamusic            |       at handleErrors (/opt/lavamusic/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
discord-lavamusic            |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
discord-lavamusic            |       at BurstHandler.runRequest (/opt/lavamusic/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
discord-lavamusic            |       at REST.request (/opt/lavamusic/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
discord-lavamusic            |       at async ChatInputCommandInteraction.reply (/opt/lavamusic/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
discord-lavamusic            |     requestBody: { files: [], json: [Object] },
discord-lavamusic            |     rawError: { message: 'Unknown interaction', code: 10062 },
discord-lavamusic            |     code: 10062,
discord-lavamusic            |     status: 404,
discord-lavamusic            |     method: 'POST',
discord-lavamusic            |     url: 'https://discord.com/api/v10/interactions/1096234073254543510/aW50ZXJhY3Rpb246MTA5NjIzNDA3MzI1NDU0MzUxMDpkalhGUXVlT091dmFkOWQ1TkdmRklReHN4OXZWV2FlaXZZa0J3TjNjRmNDRW82SFVyWFZGbGY0cjB0cTlkMkgyMVJwcXBVRGlQSTV6OElsOWNYY0tyV2cyTUlwTDduUjhacU8xQjZpREJCWkw0b1RJZ0hDejRYbHRMZVBidFVVWQ/callback'
discord-lavamusic            |   }
discord-lavamusic            | } reason: DiscordAPIError[10062]: Unknown interaction
discord-lavamusic            |     at handleErrors (/opt/lavamusic/node_modules/@discordjs/rest/src/lib/handlers/Shared.ts:152:10)
discord-lavamusic            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
discord-lavamusic            |     at BurstHandler.runRequest (/opt/lavamusic/node_modules/@discordjs/rest/src/lib/handlers/BurstHandler.ts:137:20)
discord-lavamusic            |     at REST.request (/opt/lavamusic/node_modules/@discordjs/rest/src/lib/REST.ts:343:20)
discord-lavamusic            |     at async ChatInputCommandInteraction.reply (/opt/lavamusic/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
discord-lavamusic            |   requestBody: { files: [], json: { type: 4, data: [Object] } },
discord-lavamusic            |   rawError: { message: 'Unknown interaction', code: 10062 },
discord-lavamusic            |   code: 10062,
discord-lavamusic            |   status: 404,
discord-lavamusic            |   method: 'POST',
discord-lavamusic            |   url: 'https://discord.com/api/v10/interactions/1096234073254543510/aW50ZXJhY3Rpb246MTA5NjIzNDA3MzI1NDU0MzUxMDpkalhGUXVlT091dmFkOWQ1TkdmRklReHN4OXZWV2FlaXZZa0J3TjNjRmNDRW82SFVyWFZGbGY0cjB0cTlkMkgyMVJwcXBVRGlQSTV6OElsOWNYY0tyV2cyTUlwTDduUjhacU8xQjZpREJCWkw0b1RJZ0hDejRYbHRMZVBidFVVWQ/callback'
discord-lavamusic            | }
```
```

**Comment by houseofbugs** [comment]
I'm getting the same on mine as well.

`[11/24/2023] [4:47:52 AM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> DiscordAPIError[10062]: Unknown interaction
      at handleErrors (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:687:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async BurstHandler.runRequest (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:786:23)
      at async _REST.request (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:1218:22)
      at async ChatInputCommandInteraction.reply (/opt/lavamusic/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
    requestBody: { files: [], json: [Object] },
    rawError: { message: 'Unknown interaction', code: 10062 },
    code: 10062,
    status: 404,
    method: 'POST',
    url: 'https://discord.com/api/v10/interactions/1177470603335303168/aW50ZXJhY3Rpb246MTE3NzQ3MDYwMzMzNTMwMzE2ODpmNHhVd3dCM2F1aGh1Tkg3RGlZeDBVVVVjWXVyMm45RnVJeGczMTFWNlFPSFA2QTFVZmFvU2VaNll5aXFwRUJabFhWd3RJcVBuODhIaXFzV0FvNUpTcThQcGxuYlV5YkRHcjhDaFFxT1ZpbEJvV1dzUVFNV0x0eVRCYWx5eFVHWA/callback'
  }
} reason: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:786:23)
    at async _REST.request (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:1218:22)
    at async ChatInputCommandInteraction.reply (/opt/lavamusic/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1177470603335303168/aW50ZXJhY3Rpb246MTE3NzQ3MDYwMzMzNTMwMzE2ODpmNHhVd3dCM2F1aGh1Tkg3RGlZeDBVVVVjWXVyMm45RnVJeGczMTFWNlFPSFA2QTFVZmFvU2VaNll5aXFwRUJabFhWd3RJcVBuODhIaXFzV0FvNUpTcThQcGxuYlV5YkRHcjhDaFFxT1ZpbEJvV1dzUVFNV0x0eVRCYWx5eFVHWA/callback'
}`
