### ISSUE TITLE
mongo 

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#44]
````
}
MongoParseError: Invalid connection string ""
    at new ConnectionString (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19)
    at parseOptions (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongodb\lib\connection_string.js:210:17)
    at new MongoClient (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongodb\lib\mongo_client.js:62:63)
    at C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\connection.js:779:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\connection.js:776:19)
    at C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\index.js:332:10
    at C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
````

**Comment by getxd-dev** [comment]
> ```
> }
> MongoParseError: Invalid connection string ""
>     at new ConnectionString (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongodb-connection-string-url\lib\index.js:66:19)
>     at parseOptions (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongodb\lib\connection_string.js:210:17)
>     at new MongoClient (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongodb\lib\mongo_client.js:62:63)
>     at C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\connection.js:779:16
>     at new Promise (<anonymous>)
>     at NativeConnection.Connection.openUri (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\connection.js:776:19)
>     at C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\index.js:332:10
>     at C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
>     at new Promise (<anonymous>)
>     at promiseOrCallback (C:\Users\abelp\Desktop\lavamusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
> ```

You need to add an MongoDB URI for the bot to function.
