### ISSUE TITLE
Error after type /play

### ISSUE THREAD

**Issue by WolverStones** [brblacky/lavamusic#458]
When I use the command /play, an error message starts spamming in the console and the song selection doesn't show up 

I use commit: https://github.com/brblacky/lavamusic/commit/34e51e6e96d7008e5623ef609cdaa6491290d91b

`[9. 5. 2023] [18:51:10] [antiCrash.js] [Lavamusic] » ✖  error     Uncaught Exception thrown: TypeError: Cannot read properties of null (reading 'id')
    at Queue.create (file:///C:/Users/pamul/Desktop/lavamusic-main/dist/structures/Queue.js:25:34)
    at InteractionCreate.run (file:///C:/Users/pamul/Desktop/lavamusic-main/dist/events/client/InteractionCreate.js:25:54)
    at Lavamusic.<anonymous> (file:///C:/Users/pamul/Desktop/lavamusic-main/dist/structures/Lavamusic.js:114:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\actions\InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:494:22)
    at WebSocketShard.onMessage (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\pamul\Desktop\lavamusic-main\node_modules\ws\lib\event-target.js:290:14)
[9. 5. 2023] [18:51:10] [aitiCrash.js] [Lavamusic] » ✖  error     Uncaught Exception thrown: TypeError: Cannot read properties of null (reading 'id')
    at Queue.create (file:///C:/Users/pamul/Desktop/lavamusic-main/dist/structures/Queue.js:25:34)
    at InteractionCreate.run (file:///C:/Users/pamul/Desktop/lavamusic-main/dist/events/client/InteractionCreate.js:25:54)
    at Lavamusic.<anonymous> (file:///C:/Users/pamul/Desktop/lavamusic-main/dist/structures/Lavamusic.js:114:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\actions\InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:494:22)
    at WebSocketShard.onMessage (C:\Users\pamul\Desktop\lavamusic-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\pamul\Desktop\lavamusic-main\node_modules\ws\lib\event-target.js:290:14)`
    
    
![ViO57nN](https://github.com/brblacky/lavamusic/assets/7571437/7d5ec6e8-592a-44ad-bb17-4ee9b0474494)
![V3EFJ4G](https://github.com/brblacky/lavamusic/assets/7571437/2fba2fe1-216b-477b-bfe1-4df57d4b53a2)

**Comment by brblacky** [comment]
Fixed issue
