### ISSUE TITLE
docker compose version not working

### ISSUE THREAD

**Issue by tomekb530** [brblacky/lavamusic#465]
Getting: ` error     Uncaught Exception thrown: Error: No nodes available, please add a node first
    at ShoukakuClient.getNode (file:///opt/lavamusic/node_modules/shoukaku/dist/index.mjs:1271:13)
    at Queue.search (file:///opt/lavamusic/dist/structures/Queue.js:51:43)
    at InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:152:53)
    at Lavamusic.<anonymous> (file:///opt/lavamusic/dist/structures/Lavamusic.js:114:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/opt/lavamusic/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/opt/lavamusic/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:354:31)
    at WebSocketManager.<anonymous> (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:238:12)
    at WebSocketManager.emit (/opt/lavamusic/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
[7/21/2023] [3:20:22 PM] [InteractionCreate.js] [Lavamusic] › ✖  error     Error: No nodes available, please add a node first
    at ShoukakuClient.getNode (file:///opt/lavamusic/node_modules/shoukaku/dist/index.mjs:1271:13)
    at Play.run (file:///opt/lavamusic/dist/commands/music/Play.js:46:106)
    at InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:142:31)
    at Lavamusic.<anonymous> (file:///opt/lavamusic/dist/structures/Lavamusic.js:114:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/opt/lavamusic/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/opt/lavamusic/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:354:31)
    at WebSocketManager.<anonymous> (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:238:12)
    at WebSocketManager.emit (/opt/lavamusic/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
[7/21/2023] [3:20:22 PM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error: No nodes available, please add a node first
    at ShoukakuClient.getNode (file:///opt/lavamusic/node_modules/shoukaku/dist/index.mjs:1271:13)
    at Queue.search (file:///opt/lavamusic/dist/structures/Queue.js:51:43)
    at InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:152:53)
    at Lavamusic.<anonymous> (file:///opt/lavamusic/dist/structures/Lavamusic.js:114:60)
    at Lavamusic.emit (node:events:513:28)
    at InteractionCreateAction.handle (/opt/lavamusic/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/opt/lavamusic/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:354:31)
    at WebSocketManager.<anonymous> (/opt/lavamusic/node_modules/discord.js/src/client/websocket/WebSocketManager.js:238:12)
    at WebSocketManager.emit (/opt/lavamusic/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)`

**Comment by WolverStones** [comment]
Error: No nodes available, please add a node.

**Comment by tomekb530** [comment]
How to add a node?

**Comment by WolverStones** [comment]
> How to add a node?

Simply read the file https://github.com/brblacky/lavamusic/blob/main/README.md thoroughly, specifically the installation process at https://github.com/brblacky/lavamusic/blob/main/README.md#-installation-using-docker-compose. This program requires Lavalink, and you can use a public one that is available by doing a quick Google search. Alternatively, you can host your own.
