### ISSUE TITLE
v3.2.0 not starting, console filled with same error.

### ISSUE THREAD

**Issue by BaxAndrei-SEC-ACC** [brblacky/lavamusic#479]
ERROR_LOG:
```
2023-10-10 13:27:14     
2023-10-10 13:27:14     █░░ ▄▀█ █░█ ▄▀█ █▀▄▀█ █░█ █▀ █ █▀▀
2023-10-10 13:27:14     █▄▄ █▀█ ▀▄▀ █▀█ █░▀░█ █▄█ ▄█ █ █▄▄
2023-10-10 13:27:14                                     
2023-10-10 13:27:14              .:::.=++=:.:-:             
2023-10-10 13:27:14             =##############*            
2023-10-10 13:27:14             *###############.           
2023-10-10 13:27:14              =++=*####*=++=:            
2023-10-10 13:27:14                  .*##*:                               
2023-10-10 13:27:14                .+######*:               
2023-10-10 13:27:14               =*#########+.             
2023-10-10 13:27:14             :*############*-            
2023-10-10 13:27:14            =################*.          
2023-10-10 13:27:14          :*##################*=         
2023-10-10 13:27:14        .+######################*:       
2023-10-10 13:27:14        *#########################.      
2023-10-10 13:27:14        .::::::::::::::::::::::::.       
2023-10-10 13:27:15 [10/10/2023] [10:27:15 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
2023-10-10 13:27:15 /opt/lavamusic/node_modules/.prisma/client/index.js:43
2023-10-10 13:27:15     throw new Error(
2023-10-10 13:27:15     ^
2023-10-10 13:27:15 
2023-10-10 13:27:15 Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
2023-10-10 13:27:15 In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
2023-10-10 13:27:15     at new PrismaClient (/opt/lavamusic/node_modules/.prisma/client/index.js:43:11)
2023-10-10 13:27:15     at Object.<anonymous> (/opt/lavamusic/dist/api/services/guilds/GuildServices.js:9:16)
2023-10-10 13:27:15     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-10-10 13:27:15     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-10-10 13:27:15     at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-10-10 13:27:15     at Module._load (node:internal/modules/cjs/loader:960:12)
2023-10-10 13:27:15     at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-10-10 13:27:15     at require (node:internal/modules/cjs/helpers:119:18)
2023-10-10 13:27:15     at Object.<anonymous> (/opt/lavamusic/dist/api/controllers/guilds/GuildControllers.js:4:25)
2023-10-10 13:27:15     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-10-10 13:27:15 
2023-10-10 13:27:15 Node.js v18.18.0
2023-10-10 13:27:16 /opt/lavamusic/node_modules/.prisma/client/index.js:43
2023-10-10 13:27:16     throw new Error(
2023-10-10 13:27:16     ^
2023-10-10 13:27:17 
2023-10-10 13:27:17 Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
2023-10-10 13:27:17 In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
2023-10-10 13:27:17     at new PrismaClient (/opt/lavamusic/node_modules/.prisma/client/index.js:43:11)
2023-10-10 13:27:17     at Object.<anonymous> (/opt/lavamusic/dist/api/services/guilds/GuildServices.js:9:16)
2023-10-10 13:27:17     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-10-10 13:27:17     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-10-10 13:27:17     at Module.load (node:internal/modules/cjs/loader:1119:32)
2023-10-10 13:27:17     at Module._load (node:internal/modules/cjs/loader:960:12)
2023-10-10 13:27:17     at Module.require (node:internal/modules/cjs/loader:1143:19)
2023-10-10 13:27:17     at require (node:internal/modules/cjs/helpers:119:18)
2023-10-10 13:27:17     at Object.<anonymous> (/opt/lavamusic/dist/api/controllers/guilds/GuildControllers.js:4:25)
2023-10-10 13:27:17     at Module._compile (node:internal/modules/cjs/loader:1256:14)
2023-10-10 13:27:17 
2023-10-10 13:27:17 Node.js v18.18.0
2023-10-10 13:27:17 /opt/lavamusic/node_modules/.prisma/client/index.js:43
2023-10-10 13:27:17     throw new Error(
2023-10-10 13:27:17     ^
```

I installed it using `docker compose up -d` (before this I edited TOKEN, PREFIX, OWNER_IDS, CLIENT_ID, GUILD_ID in docker-compose.json

**Comment by BaxAndrei-SEC-ACC** [comment]
TEMP FIX:

docker exec lavamusic container and execute:
```
apt-get update -y && apt-get install -y openssl
npx prisma generate
```

then exit container and execute docker compose restart

**Comment by houseofbugs** [comment]
This works but how can we perma fix this?

**Comment by BaxAndrei** [comment]
It must be done by the author of the docker image, he must modify the image to execute those commands when creating the image.
