### ISSUE TITLE
PrismaClientInitializationError, [Glitch Remix]

### ISSUE THREAD

**Issue by bimaindrawans** [brblacky/lavamusic#486]
![image](https://github.com/brblacky/lavamusic/assets/147312348/526e1038-3cfb-4a19-8fed-d64fa6a6dbdc)

but i got this error, when using glitch, should i use node.js v18 ?

```[11/26/2023] [4:40:44 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
[11/26/2023] [4:40:47 AM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded commands!
[11/26/2023] [4:40:47 AM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded events!
[11/26/2023] [4:40:48 AM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: Advice Plugin v1.0.0
[11/26/2023] [4:40:48 AM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: AntiCrash Plugin v1.0.0
[11/26/2023] [4:40:48 AM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: KeepAlive Plugin v1.0.0
[11/26/2023] [4:40:48 AM] [keepAlive.js] [Lavamusic] › ℹ  info      Keep-Alive server is running on port 3000
[11/26/2023] [4:40:48 AM] [Lavamusic.js] [Lavamusic] › ✖  error     Unable to connect to the database!
[11/26/2023] [4:40:48 AM] [Lavamusic.js] [Lavamusic] › ✖  error     PrismaClientInitializationError: error: Error validating datasource `db`: the URL must start with the protocol `mongo`. 
  -->  schema.prisma:11
   | 
10 |   provider = "mongodb"
11 |   url      = env("DATABASE_URL")
   | 
Validation Error Count: 1
    at r (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:115:2752)
[11/26/2023] [4:40:48 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
[11/26/2023] [4:40:48 AM] [Ready.js] [Lavamusic] › ✔  success   I-BOT#3706 is ready!
[11/26/2023] [4:40:49 AM] [NodeConnect.js] [Lavamusic] › ✔  success   Node local is ready!
[11/26/2023] [4:40:49 AM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> PrismaClientInitializationError: 
  Invalid `prisma.stay.findMany()` invocation:
  
  
  error: Error validating datasource `db`: the URL must start with the protocol `mongo`.
    -->  schema.prisma:11
     | 
  10 |   provider = "mongodb"
  11 |   url      = env("DATABASE_URL")
     | 
  
  Validation Error Count: 1
      at ni.handleRequestError (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:124:7090)
      at ni.handleAndLogRequestError (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)
      at ni.request (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)
      at async l (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023)
      at async NodeConnect.run (file:///app/dist/events/player/NodeConnect.js:10:22) {
    clientVersion: '5.6.0',
    errorCode: undefined
  }
} reason: PrismaClientInitializationError: 
Invalid `prisma.stay.findMany()` invocation:
error: Error validating datasource `db`: the URL must start with the protocol `mongo`.
  -->  schema.prisma:11
   | 
10 |   provider = "mongodb"
11 |   url      = env("DATABASE_URL")
   | 
Validation Error Count: 1
    at ni.handleRequestError (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:124:7090)
    at ni.handleAndLogRequestError (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)
    at ni.request (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)
    at async l (/rbd/pnpm-volume/92140cb1-7833-4593-8007-64e8e2c63c2e/node_modules/.registry.npmjs.org/@prisma/client/5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023)
    at async NodeConnect.run (file:///app/dist/events/player/NodeConnect.js:10:22) {
  clientVersion: '5.6.0',
  errorCode: undefined
}
```

when i try to use a command, it show
![image](https://github.com/brblacky/lavamusic/assets/147312348/83d65609-ff5e-4208-a035-26de1c07cb48)

**Comment by brblacky** [comment]
your database url is wrong
