### ISSUE TITLE
Can't play online radio on 4.0.2 update

### ISSUE THREAD

**Issue by codemeister64** [brblacky/lavamusic#493]
Hi! 
After latests update v4.0.2 I can't play online-radio. At the same time, youtube search works fine.

Exampe:

`
!play http://s3.radionetz.de:80/1a-rock.mp3
`

And in a logs I can see the following exception:

`
[12/30/2023] [6:13:45 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Blacky is ready!
[12/30/2023] [6:17:03 PM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error: Track is not provided
    at new Song (file:///opt/lavamusic/dist/structures/Dispatcher.js:4:19)
    at Dispatcher.buildTrack (file:///opt/lavamusic/dist/structures/Dispatcher.js:148:16)
    at Play.run (file:///opt/lavamusic/dist/commands/music/Play.js:70:38)
`

In a lavalink logs there are no errors:

`
2023-12-30T18:17:03.327Z  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "http://s3.radionetz.de:80/1a-rock.mp3"
2023-12-30T18:17:03.993Z  INFO 1 --- [  XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded track Rock, Metal, Alternative und Crossover zum Aufdrehen und Abgehen.
2023-12-30T18:17:03.996Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=http%3A%2F%2Fs3.radionetz.de%3A80%2F1a-rock.mp3, client=172.18.0.4
2023-12-30T18:17:15.522Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version, client=127.0.0.1
`

**Comment by brblacky** [comment]
Fixed
