### ISSUE TITLE
LavaLink Error

### ISSUE THREAD

**Issue by YashRawat911** [brblacky/lavamusic#494]
```
TypeError: Cannot read properties of null (reading 'players')
    at file:///home/container/Music/dist/commands/info/LavaLink.js:41:72
    at Map.forEach (<anonymous>)
    at LavaLink.run (file:///home/container/Music/dist/commands/info/LavaLink.js:35:31)
    at InteractionCreate.run (file:///home/container/Music/dist/events/client/InteractionCreate.js:149:31)
    at Lavamusic.<anonymous> (file:///home/container/Music/dist/structures/Lavamusic.js:133:60)
    at Lavamusic.emit (node:events:529:35)
    at InteractionCreateAction.handle (/home/container/Music/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/container/Music/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/container/Music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)
    at WebSocketManager.<anonymous> (/home/container/Music/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)
```

**Comment by brblacky** [comment]
it is your lavalink issue
