### ISSUE TITLE
Problems while running thru docker

### ISSUE THREAD

**Issue by xemulat** [brblacky/lavamusic#495]
I downloaded the latest docker-compose.yml template and deployed it on my server, after starting it started to display these errors:
```
            :*############*-            
           =################*.          
         :*##################*=         
       .+######################*:       
       *#########################.      
       .::::::::::::::::::::::::.       
[1/1/2024] [1:01:31 PM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
[1/1/2024] [1:01:31 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded commands!
[1/1/2024] [1:01:31 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded events!
[1/1/2024] [1:01:31 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: Advice Plugin v1.0.0
[1/1/2024] [1:01:31 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: AntiCrash Plugin v1.0.0
[1/1/2024] [1:01:31 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: KeepAlive Plugin v1.0.0
[1/1/2024] [1:01:32 PM] [Lavamusic.js] [Lavamusic] › ✔  success   Connected to the database!
[1/1/2024] [1:01:40 PM] [index.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
[1/1/2024] [1:01:40 PM] [Ready.js] [Lavamusic] › ✔  success   XXXX#0000 is ready!
[1/1/2024] [1:01:40 PM] [NodeConnect.js] [Lavamusic] › ✔  success   Node Blacky is ready!
[1/1/2024] [1:01:40 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded slash commands!
[1/1/2024] [1:01:43 PM] [antiCrash.js] [Lavamusic] › ✖  error     Unhandled Rejection at: Promise {
  <rejected> PrismaClientKnownRequestError: 
  Invalid `prisma.stay.findMany()` invocation:
  
  
  Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 13436 (NotPrimaryOrSecondary): node is not in primary or recovering state, labels: {}`
      at si.handleRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:125:6817)
      at si.handleAndLogRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:125:6151)
      at si.request (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:125:5859)
      at async l (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:130:10025)
      at async NodeConnect.run (file:///opt/lavamusic/dist/events/player/NodeConnect.js:10:22) {
    code: 'P2010',
    clientVersion: '5.7.1',
    meta: {
      modelName: 'stay',
      code: 'unknown',
      message: 'Kind: Command failed: Error code 13436 (NotPrimaryOrSecondary): node is not in primary or recovering state, labels: {}'
    }
  }
} reason: PrismaClientKnownRequestError: 
Invalid `prisma.stay.findMany()` invocation:
Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 13436 (NotPrimaryOrSecondary): node is not in primary or recovering state, labels: {}`
    at si.handleRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/opt/lavamusic/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async NodeConnect.run (file:///opt/lavamusic/dist/events/player/NodeConnect.js:10:22) {
  code: 'P2010',
  clientVersion: '5.7.1',
      
{
    modelName: 'stay',
    code: 'unknown',
    message: 'Kind: Command failed: Error code 13436 (NotPrimaryOrSecondary): node is not in primary or recovering state, labels: {}'
  }
}
[1/1/2024] [1:02:09 PM] [InteractionCreate.js] [Lavamusic] › ✖  error     DiscordAPIError[10062]: Unknown interaction 
    at handleErrors (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.deferReply (/opt/lavamusic/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
    at async Context.sendDeferMessage (file:///opt/lavamusic/dist/structures/Context.js:55:24)
    at async Ping.run (file:///opt/lavamusic/dist/commands/info/Ping.js:31:21)
    at async InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:149:17)
[1/1/2024] [1:02:13 PM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/opt/lavamusic/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.reply (/opt/lavamusic/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async InteractionCreate.run (file:///opt/lavamusic/dist/events/client/InteractionCreate.js:153:17) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/00000000/XXXXXXXXXXX/callback'
}
```

**Comment by brblacky** [comment]
fixed e22f6a01600506fb12c08c56ab78d456a1880d5e
