### ISSUE TITLE
Latest version - Bot Joins and Leaves - Node Errors in log file.

### ISSUE THREAD

**Issue by houseofbugs** [brblacky/lavamusic#497]
Went to use the music bot today and it just joins then leaves. Already updated my compose file. Any ideas?

```
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Fetched 100 kB in 4s (22.7 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
openssl is already the newest version (3.0.11-1~deb12u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

 
    █░░ ▄▀█ █░█ ▄▀█ █▀▄▀█ █░█ █▀ █ █▀▀
    █▄▄ █▀█ ▀▄▀ █▀█ █░▀░█ █▄█ ▄█ █ █▄▄
                                    
             .:::.=++=:.:-:             
            =##############*            
            *###############.           
             =++=*####*=++=:            
                 .*##*:                               
               .+######*:               
              =*#########+.             
            :*############*-            
           =################*.          
         :*##################*=         
       .+######################*:       
       *#########################.      
       .::::::::::::::::::::::::.       
[1/3/2024] [9:36:29 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
[1/3/2024] [9:36:29 AM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded commands!
[1/3/2024] [9:36:29 AM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded events!
[1/3/2024] [9:36:29 AM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: KeepAlive Plugin v1.0.0
[1/3/2024] [9:36:29 AM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: AntiCrash Plugin v1.0.0
[1/3/2024] [9:36:29 AM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: Advice Plugin v1.0.0
[1/3/2024] [9:36:30 AM] [Lavamusic.js] [Lavamusic] › ✔  success   Connected to the database!
[1/3/2024] [9:36:38 AM] [index.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
[1/3/2024] [9:36:38 AM] [Ready.js] [Lavamusic] › ✔  success   Tim's Music Bot#1517 is ready!
[1/3/2024] [9:36:38 AM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded slash commands!
[1/3/2024] [9:37:08 AM] [antiCrash.js] [Lavamusic] › ✖  error     Uncaught Exception thrown: Error: Can't find any nodes to connect on
    at ShoukakuClient.joinVoiceChannel (file:///opt/lavamusic/node_modules/shoukaku/dist/index.mjs:1323:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Queue.create (file:///opt/lavamusic/dist/structures/Queue.js:29:28)
    at async Play.run (file:///opt/lavamusic/dist/commands/music/Play.js:47:22)
```

**Comment by houseofbugs** [comment]
Thought it was the docker compose missing `npx prisma generate && ` from the command line but that was not it. Any ideas?

**Comment by houseofbugs** [comment]
Figured it out. You still have to have these in the compose file: 

There is a new compose file format and it was not working. Used this one here: https://github.com/BaxAndrei/lavamusic/blob/main/docker-compose.yml 

The one linked on the main github page is this one (it doesn't work for me): https://raw.githubusercontent.com/brblacky/lavamusic/main/docker-compose.yml

```

      LAVALINK_SERVER_PASSWORD: "youshallnotpass"
      LAVALINK_SERVER_SOURCES_YOUTUBE: "true"
      LAVALINK_SERVER_SOURCES_BANDCAMP: "true"
      LAVALINK_SERVER_SOURCES_SOUNDCLOUD: "true"
      LAVALINK_SERVER_SOURCES_TWITCH: "true"
      LAVALINK_SERVER_SOURCES_VIMEO: "true"
      LAVALINK_SERVER_SOURCES_HTTP: "true"
      LAVALINK_SERVER_SOURCES_LOCAL: "false"
      LAVALINK_SERVER_BUFFER_DURATION_MS: 400
      LAVALINK_SERVER_FRAME_BUFFER_DURATIONS_MS: 5000
      LAVALINK_SERVER_TRACK_STRUCK_THRESHOLD_MS: 10000
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: 6
      LAVALINK_SERVER_PLAYER_UPDATE_INTERVAL: 5
      LAVALINK_SERVER_YOUTUBE_SEARCH_ENABLED: "true"
      LAVALINK_SERVER_SOUNDCLOUD_SEARCH_ENABLED: "true"
      #LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL:
      #LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD:
      LAVALINK_SERVER_SENTRY_DSN: ""
```

**Comment by brblacky** [comment]
You have to add application.yml in Lavalink folder

**Comment by brblacky** [comment]
> Thought it was the docker compose missing `npx prisma generate && ` from the command line but that was not it. Any ideas?

I don't think so I tried in lavamusic bot it is working and online
