### ISSUE TITLE
Windows 11 localhost problem

### ISSUE THREAD

**Issue by delidolu1adam** [brblacky/lavamusic#514]
I want to invite the official version of the bot to my discord server. However, I encounter an error, I think the allowed server limit has been exceeded.

I tried to run the bot on locahost server in windows 11 but I encountered a problem and I still couldn't fix the problem.

Java Version: jdk-17.0.10_windows-x64_bin.exe
Lavalink Release: https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.3

Lavalink: https://imgur.com/csl1rwI

Bot: https://imgur.com/cFRiAAq

Discord Channel: https://imgur.com/ESGNn1T

Lavalink/Lavalink.jar
Lavalink/application.yml: https://pastebin.com/N94M1hfK

LAVALINK_URL="127.0.0.1:8080" # Your lavalink url
LAVALINK_AUTH="youshallnotpass" # Your lavalink password

**Comment by Sebaxhino** [comment]
[3/8/2024] [8:46:55 PM] [antiCrash.js] [LavaMusic] › ✖  error     Uncaught Exception thrown: Error: This guild already have an existing connection
    at ShoukakuClient.joinVoiceChannel (file:///home/debian/Desktop/LavaMusic/node_modules/shoukaku/dist/index.mjs:1311:13)
    at Queue.create (file:///home/debian/Desktop/LavaMusic/dist/structures/Queue.js:29:55)
    at SetupSystem.run (file:///home/debian/Desktop/LavaMusic/dist/events/client/SetupSystem.js:38:46)
    at LavaMusic.<anonymous> (file:///home/debian/Desktop/LavaMusic/dist/structures/LavaMusic.js:120:60)
    at LavaMusic.emit (node:events:519:28)
    at MessageCreate.run (file:///home/debian/Desktop/LavaMusic/dist/events/client/MessageCreate.js:15:36)
    at LavaMusic.<anonymous> (file:///home/debian/Desktop/LavaMusic/dist/structures/LavaMusic.js:120:60)
    at LavaMusic.emit (node:events:531:35)
    at MessageCreateAction.handle (/home/debian/Desktop/LavaMusic/node_modules/discord.js/src/client/actions/MessageCreate.js:28:14)
    at module.exports [as MESSAGE_CREATE] (/home/debian/Desktop/LavaMusic/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[3/8/2024] [8:47:02 PM] [antiCrash.js] [LavaMusic] › ✖  error     Uncaught Exception thrown: Error: The voice connection is not established in 15 seconds
    at Connection.connect (file:///home/debian/Desktop/LavaMusic/node_modules/shoukaku/dist/index.mjs:335:15)
    at async ShoukakuClient.joinVoiceChannel (file:///home/debian/Desktop/LavaMusic/node_modules/shoukaku/dist/index.mjs:1315:7)
    at async Queue.create (file:///home/debian/Desktop/LavaMusic/dist/structures/Queue.js:29:28)
    at async SetupSystem.run (file:///home/debian/Desktop/LavaMusic/dist/events/client/SetupSystem.js:38:22)
