### ISSUE TITLE
GuildDelete error

### ISSUE THREAD

**Issue by AbelCode1** [brblacky/lavamusic#67]
DiscordAPIError: Missing Access
    at RequestHandler.execute (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async GuildMemberManager._fetchSingle (/var/lib/pufferpanel/servers/6a3aa38e/node_modules/discord.js/src/managers/GuildMemberManager.js:388:18)
    at async module.exports (/var/lib/pufferpanel/servers/6a3aa38e/src/events/Client/guildDelete.js:7:13) {
  method: 'get',
  path: '/guilds/860203790426570812/members/809213892857167942',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }

**Comment by Armxxn34** [comment]
pretty sure ur bot is missing permissions

**Comment by AbelCode1** [comment]
> pretty sure ur bot is missing permissions

Its an administrator

**Comment by chethanyadav456** [comment]
Give the permissions to u r bot.
